### ISSUE TITLE
Circular import?

### ISSUE THREAD

**Issue by da-wad** [equinor/oneseismic#507]
Seems to only affect Windows, but the second line of the example code from the readme appears not to work...

```
Python 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import oneseismic
>>> import oneseismic.simple as simple
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Appl\repos\oneseismic\python\oneseismic\simple\__init__.py", line 10, in <module>
    from .simple_client import simple_client
  File "C:\Appl\repos\oneseismic\python\oneseismic\simple\simple_client.py", line 9, in <module>
    import oneseismic.decoding as decoding
  File "C:\Appl\repos\oneseismic\python\oneseismic\decoding\__init__.py", line 1, in <module>
    from .decoding import decode_stream
  File "C:\Appl\repos\oneseismic\python\oneseismic\decoding\decoding.py", line 3, in <module>
    from . import decoder
ImportError: cannot import name 'decoder' from partially initialized module 'oneseismic.decoding' (most likely due to a circular import) (C:\Appl\repos\oneseismic\python\oneseismic\decoding\__init__.py)```

**Comment by achaikou** [comment]
Hm. Clean install of `oneseismic-0.3.1` through pip  works for me on similar environment.
```
Python 3.8.10 (default, May 19 2021, 13:12:57) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import oneseismic
>>> import oneseismic.simple as simple
>>>
```

**Comment by da-wad** [comment]
If you're using Conda you might have a rather different set of package versions... I'd be interested to know if so!

Here's mine:

```
(oneseismic_py38) PS C:\Appl> pip list
Package            Version
------------------ ---------
azure-core         1.20.1
azure-identity     1.7.1
azure-storage-blob 12.9.0
certifi            2021.10.8
cffi               1.15.0
charset-normalizer 2.0.7
colorama           0.4.4
cryptography       35.0.0
gql                2.0.0
graphql-core       2.3.2
idna               3.3
isodate            0.6.0
msal               1.16.0
msal-extensions    0.3.0
msrest             0.6.21
numpy              1.21.4
oauthlib           3.1.1
oneseismic         0.3.1
pandas             1.3.4
pip                21.1.1
portalocker        1.7.1
promise            2.3
pycparser          2.21
PyJWT              2.3.0
python-dateutil    2.8.2
pytz               2021.3
pywin32            302
requests           2.26.0
requests-oauthlib  1.3.0
Rx                 1.6.1
segyio             1.9.7
setuptools         56.0.0
six                1.16.0
tqdm               4.62.3
urllib3            1.26.7
xarray             0.20.1
```

**Comment by achaikou** [comment]
Seems similar enough. I have `wheel` and `wincertstore` packages, and a bit different version of `setuptools` and `pip`. Everything else is the same.
```
(py3810) PS C:\dev> pip list
Package            Version
------------------ ---------
azure-core         1.20.1
azure-identity     1.7.1
azure-storage-blob 12.9.0
certifi            2021.10.8
cffi               1.15.0
charset-normalizer 2.0.7
colorama           0.4.4
cryptography       35.0.0
gql                2.0.0
graphql-core       2.3.2
idna               3.3
isodate            0.6.0
msal               1.16.0
msal-extensions    0.3.0
msrest             0.6.21
numpy              1.21.4
oauthlib           3.1.1
oneseismic         0.3.1
pandas             1.3.4
pip                21.2.2
portalocker        1.7.1
promise            2.3
pycparser          2.21
PyJWT              2.3.0
python-dateutil    2.8.2
pytz               2021.3
pywin32            302
requests           2.26.0
requests-oauthlib  1.3.0
Rx                 1.6.1
segyio             1.9.7
setuptools         58.0.4
six                1.16.0
tqdm               4.62.3
urllib3            1.26.7
wheel              0.37.0
wincertstore       0.2
xarray             0.20.1
```

**Comment by da-wad** [comment]
Upgraded `setuptools` to 0.59.1 and as if by magic the import worked... not sure whether/where you specify a `setup_requires` anywhere?

**Comment by achaikou** [comment]
I am not familiar enough with the build/install configuration of oneseismic, but it looks like it is not used (@sveinung-r  please correct me if I am wrong).
We are using skbuild to build the project, but it shouldn't matter, I believe, as you use the pip package.

Anyway, I am not sure it's related.
I downgraded setuptools and still don't get the error 

```
(py3810-2) PS C:\dev> pip list
Package            Version
------------------ ---------
...
setuptools         56.0.0
...
```

```
(py3810-2) PS C:\dev> python
Python 3.8.10 (default, May 19 2021, 13:12:57) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import oneseismic
>>> import oneseismic.simple as simple
>>>
```
